### PR TITLE
ready_for_review : Update package-lock.json

### PR DESCRIPTION
**Pull request by naman-tiwari**

### CODE REVIEW

**Review by naman-tiwari — COMMENTED** [review]
from line number 29506 to 29518 code review is required(update) and same therefore from line 53871 to 53876

**Comment by mcturco** [comment]
Hi @naman-tiwari! A few things:
- It would help give context to your changes if you updated the description of the PR explaining why the changes are necessary
- You are missing the Lint title in the PR, ([see here for breakdown of available ones](https://github.com/asyncapi/design-system/runs/6322096638?check_suite_focus=true)) Looks like you are updating packages so might be best to go with the `build:` title prefix
- Not sure that we need the `.vscode` files and I think that they should probably be added to .gitignore. Keep in mind that not everyone uses vscode as an IDE, so unless this file absolutely has to be part of the base repo, I would say to remove it.

It might help to have @magicmatatjahu's feedback here as well 😄

**Comment by naman-tiwari** [comment]
Ok @mcturco

**Review by fmvilas — CHANGES_REQUESTED** [review]
Yeah, please provide the following information:

1. Why are you changing package-lock.json.
2. Remove the `.vscode/launch.json` file from the PR. This is part of your laptop configuration and should not be pushed.

Next time, please create an issue first explaining what you want to do, and then once we come up with an agreement you can create the PR.

Also, I'm always hesitant of approving PRs that modify package-lock.json. There are multiple security vulnerabilities that can be easily introduced by manipulating the file manually. It's ok to update it if needed but at least provide a strong reason to do it.

Cheers!

**Comment by fmvilas** [comment]
Sounds good. No problem 👍

**Pull request closed without merging**
